/**
 * Block icons
 */

const blockIcons = {};

blockIcons.bbutton = (
  <svg width="20" height="20" xmlns="http://www.w3.org/2000/svg">
    <g>
      <rect
        fill="#fff"
        id="canvas_background"
        height="402"
        width="582"
        y="-1"
        x="-1"
      />
    </g>
    <g>
      <rect
        id="svg_background"
        height="20.0625"
        width="20.0625"
        y="0.027083"
        x="-0.010416"
        fillOpacity="null"
        strokeOpacity="null"
        strokeWidth="2"
        stroke="#0f0f00"
        fill="#fff"
      />
      <rect
        id="svg_fill"
        height="0"
        width="1.125"
        y="17.027083"
        x="13.364584"
        fillOpacity="null"
        strokeOpacity="null"
        strokeWidth="2"
        stroke="#0f0f00"
        fill="#fff"
      />
      <rect
        id="svg_rect"
        height="1.5"
        width="15.375"
        y="15.277083"
        x="2.364584"
        fillOpacity="null"
        strokeOpacity="null"
        strokeWidth="2"
        stroke="#0f0f00"
        fill="#fff"
      />
    </g>
  </svg>
);

blockIcons.dashed = (
  <svg width="20" height="20" xmlns="http://www.w3.org/2000/svg">
    <g>
      <rect
        fill="#fff"
        id="canvas_background"
        height="402"
        width="582"
        y="-1"
        x="-1"
      />
    </g>
    <g>
      <rect
        strokeDasharray="2,2"
        id="svg_background"
        height="20.0625"
        width="20.0625"
        y="0.027083"
        x="-0.010416"
        fillOpacity="null"
        strokeOpacity="null"
        strokeWidth="2"
        stroke="#0f0f00"
        fill="#fff"
      />
      <rect
        id="svg_fill"
        height="0"
        width="1.125"
        y="17.027083"
        x="13.364584"
        fillOpacity="null"
        strokeOpacity="null"
        strokeWidth="2"
        stroke="#0f0f00"
        fill="#fff"
      />
      <rect
        id="svg_rect"
        height="0.250001"
        width="7.9375"
        y="16.214583"
        x="6.03125"
        fillOpacity="null"
        strokeOpacity="null"
        strokeWidth="2"
        stroke="#0f0f00"
        fill="#fff"
      />
    </g>
  </svg>
);

blockIcons.minimalist = (
  <svg width="20" height="20" xmlns="http://www.w3.org/2000/svg">
    <g>
      <rect
        fill="#fff"
        id="canvas_background"
        height="402"
        width="582"
        y="-1"
        x="-1"
      />
    </g>
    <g>
      <rect
        id="svg_background"
        height="20.0625"
        width="20.0625"
        y="0.027083"
        x="-0.010416"
        fillOpacity="null"
        strokeOpacity="null"
        strokeWidth="2"
        stroke="#0f0f00"
        fill="#fff"
      />
      <rect
        id="svg_fill"
        height="0"
        width="1.125"
        y="17.027083"
        x="13.364584"
        fillOpacity="null"
        strokeOpacity="null"
        strokeWidth="2"
        stroke="#0f0f00"
        fill="#fff"
      />
      <rect
        id="svg_rect"
        height="0.250001"
        width="7.9375"
        y="16.214583"
        x="6.03125"
        fillOpacity="null"
        strokeOpacity="null"
        strokeWidth="2"
        stroke="#0f0f00"
        fill="#fff"
      />
    </g>
  </svg>
);

export default blockIcons;
